# Generated by Django 5.2.6 on 2025-09-05 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('canal', models.CharField(choices=[('02 Canal Tradicional', '02 Canal Tradicional'), ('05 Canal Mayorista', '05 Canal Mayorista')], default='02 Canal Tradicional', max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Cuestionario', max_length=255)),
                ('canal', models.CharField(choices=[('02 Canal Tradicional', '02 Canal Tradicional'), ('05 Canal Mayorista', '05 Canal Mayorista')], default='02 Canal Tradicional', max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('puntos_maximos', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('Breve', 'Sí / No'), ('Breve1', 'Sí / No / N/D')], default='Breve', max_length=20)),
                ('camara', models.IntegerField(choices=[(0, 'Sin cámara'), (1, 'Sí (si responde Sí)'), (2, 'No (si responde No)'), (3, 'N/D (si responde No Aplica)'), (4, 'Siempre requiere foto'), (5, 'Sí o N/D')], default=0)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Portafolio_v2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('puntos_maximos', models.IntegerField(default=0)),
                ('porcentaje_ejecucion', models.FloatField(default=0.0)),
                ('porcentaje_contestado', models.FloatField(default=0.0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolios', to='inventario.cliente')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolios', to='inventario.cuestionario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portafolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portafolio (Auditoría)',
                'verbose_name_plural': 'Portafolios (Auditorías)',
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[(1, 'select'), (2, 'radio'), (3, 'checkbox')], default='2', max_length=20)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='inventario.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('opcion_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='inventario.opcionrespuesta')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='inventario.portafolio_v2')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='inventario.pregunta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Imagen_Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes', to=settings.AUTH_USER_MODEL)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.respuesta')),
            ],
            options={
                'verbose_name': 'Imagen de Respuesta',
                'verbose_name_plural': 'Imágenes de Respuesta',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('puntos_maximos', models.IntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='inventario.cuestionario')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='inventario.seccion'),
        ),
        migrations.CreateModel(
            name='PortafolioSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('porcentaje_ejecucion', models.FloatField(default=0.0)),
                ('porcentaje_contestado', models.FloatField(default=0.0)),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='inventario.portafolio_v2')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='inventario.seccion')),
            ],
            options={
                'verbose_name': 'Resultado por Sección',
                'verbose_name_plural': 'Resultados por Sección',
            },
        ),
    ]
