# Generated by Django 5.2.6 on 2025-09-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='tipo',
            field=models.CharField(choices=[('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox')], default='radio', max_length=20),
        ),
    ]
